name: auth
description: "A pacage to authenticate users using bloc and firebase"
version: 0.0.1
publish_to: 'none'
homepage: null

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^5.4.5
  commons:
    path: ../commons
  firebase_auth: ^5.3.2
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.2
  go_router: ^14.6.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  mockito: ^5.4.4

flutter: null
