name: commons
description: "A package that contains common widgets and utilities for Flutter applications."
version: 0.0.1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.2
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2


flutter:
