name: commons
description: "A package that contains common widgets and utilities for Flutter
  applications."
version: 0.0.1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
homepage: null

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.4.1
  calendar_date_picker2: ^1.1.7
  cloud_firestore: ^5.4.5
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.2
  lottie: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2

flutter: 

  assets:
    - assets/
    - assets/fonts/

