// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxbVEpZIdKMq0IJOgClxwU38nQg1Tkj7w',
    appId: '1:210542296187:web:313fa4c6c68d52441cb6de',
    messagingSenderId: '210542296187',
    projectId: 'medicos-honestos',
    authDomain: 'medicos-honestos.firebaseapp.com',
    storageBucket: 'medicos-honestos.firebasestorage.app',
    measurementId: 'G-9E77YWF74M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBltSwEYZ-AQHN5d2en4pTZbuVLheZky-A',
    appId: '1:210542296187:android:bdf992a9734757131cb6de',
    messagingSenderId: '210542296187',
    projectId: 'medicos-honestos',
    storageBucket: 'medicos-honestos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs7vPhMPJJS1Yf4L1IUm610KDYiI53cgA',
    appId: '1:210542296187:ios:c6edd6478f51d1a91cb6de',
    messagingSenderId: '210542296187',
    projectId: 'medicos-honestos',
    storageBucket: 'medicos-honestos.firebasestorage.app',
    iosBundleId: 'com.example.medicalLinkTree',
  );
}
